const sampleStudents = [
  {
    name: "Rahul Sharma",
    email: "rahul1@gmail.com",
    phone: "9876543210",
    address: "123 MG Road, Pune",
    parentMobile: "9123456780",
    roomNo: 101,
    course: "B.Tech",
    branch: "CSE",
    fine: 0,
    feeStatus: "Pending",
    image: "https://randomuser.me/api/portraits/men/1.jpg"
  },
  {
    name: "Priya Verma",
    email: "priya2@gmail.com",
    phone: "9123456781",
    address: "45 FC Road, Pune",
    parentMobile: "9876543211",
    roomNo: 102,
    course: "B.Tech",
    branch: "IT",
    fine: 50,
    feeStatus: "Paid",
    image: "https://randomuser.me/api/portraits/women/2.jpg"
  },
  {
    name: "Amit Singh",
    email: "amit3@gmail.com",
    phone: "9988776655",
    address: "22 JM Road, Pune",
    parentMobile: "9988776656",
    roomNo: 103,
    course: "B.Tech",
    branch: "MECH",
    fine: 100,
    feeStatus: "Pending",
    image: "https://randomuser.me/api/portraits/men/3.jpg"
  },
  {
    name: "Neha Gupta",
    email: "neha4@gmail.com",
    phone: "9876543222",
    address: "78 LK Road, Pune",
    parentMobile: "9123456799",
    roomNo: 104,
    course: "B.Tech",
    branch: "Civil",
    fine: 0,
    feeStatus: "Paid",
    image: "https://randomuser.me/api/portraits/women/4.jpg"
  },
  {
    name: "Rohan Patel",
    email: "rohan5@gmail.com",
    phone: "9876543233",
    address: "11 MG Road, Pune",
    parentMobile: "9123456700",
    roomNo: 105,
    course: "B.Tech",
    branch: "ECM",
    fine: 25,
    feeStatus: "Pending",
    image: "https://randomuser.me/api/portraits/men/5.jpg"
  },
  {
    name: "Sakshi Mehta",
    email: "sakshi6@gmail.com",
    phone: "9876543244",
    address: "33 FC Road, Pune",
    parentMobile: "9123456711",
    roomNo: 106,
    course: "B.Tech",
    branch: "CSE",
    fine: 0,
    feeStatus: "Paid",
    image: "https://randomuser.me/api/portraits/women/6.jpg"
  },
  {
    name: "Aditya Yadav",
    email: "aditya7@gmail.com",
    phone: "9876543255",
    address: "44 JM Road, Pune",
    parentMobile: "9123456722",
    roomNo: 107,
    course: "B.Tech",
    branch: "IT",
    fine: 10,
    feeStatus: "Pending",
    image: "https://randomuser.me/api/portraits/men/7.jpg"
  },
  {
    name: "Pooja Sharma",
    email: "pooja8@gmail.com",
    phone: "9876543266",
    address: "55 LK Road, Pune",
    parentMobile: "9123456733",
    roomNo: 108,
    course: "B.Tech",
    branch: "MECH",
    fine: 0,
    feeStatus: "Paid",
    image: "https://randomuser.me/api/portraits/women/8.jpg"
  },
  {
    name: "Vikram Rao",
    email: "vikram9@gmail.com",
    phone: "9876543277",
    address: "66 MG Road, Pune",
    parentMobile: "9123456744",
    roomNo: 109,
    course: "B.Tech",
    branch: "Civil",
    fine: 50,
    feeStatus: "Pending",
    image: "https://randomuser.me/api/portraits/men/9.jpg"
  },
  {
    name: "Ankita Jain",
    email: "ankita10@gmail.com",
    phone: "9876543288",
    address: "77 FC Road, Pune",
    parentMobile: "9123456755",
    roomNo: 110,
    course: "B.Tech",
    branch: "ECM",
    fine: 0,
    feeStatus: "Paid",
    image: "https://randomuser.me/api/portraits/women/10.jpg"
  }
];

module.exports = sampleStudents;